- name: Services
  columns:
    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Home Assistant
              url: http://ha.lan:8123
              icon: di:home-assistant
            - title: AdGuard Home
              url: http://192.168.0.1:3000
              icon: di:adguard-home
            - title: Immich
              url: http://vega.lan:8082
              icon: di:immich
            - title: Nextcloud
              url: https://nextcloud.paillaugue.fr
              icon: di:nextcloud
            - title: Jellyfin
              url: http://mars.lan:8080
              icon: di:jellyfin
            - title: Vaultwarden
              url: http://vega.lan:8081
              icon: di:vaultwarden
            - title: Open WebUI
              url: http://saturn.lan:8084/
              icon: di:open-webui-light
            - title: 4get
              url: http://saturn.lan:8089/
              icon: di:google

        - type: monitor
          cache: 1m
          title: TV
          sites:
            - title: Transmission
              url: http://mars.lan:8083
              icon: di:transmission
            - title: Jellyfin
              url: http://mars.lan:8080
              icon: di:jellyfin
            - title: Sonarr
              url: http://mars.lan:8090
              icon: di:sonarr
            - title: Radarr
              url: http://mars.lan:8091
              icon: di:radarr
            - title: Bazarr
              url: http://mars.lan:8092
              icon: di:bazarr
            - title: Jackett
              url: http://mars.lan:8093/UI/Dashboard
              icon: di:jackett
            - title: Prowlarr
              url: http://mars.lan:8096
              icon: di:prowlarr
            - title: Jellyseerr
              url: http://mars.lan:8094
              icon: di:jellyseerr
