entryPoints:
  ssh:
    address: ":22"
  web:
    address: ":80"
  websecure:
    address: ":443"
api:
  insecure: true
providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
log:
  level: DEBUG
