services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:latest
    container_name: swingmusic
    volumes:
      - /mnt/hdd2/Music:/music
      - .config:/config
    ports:
      - "1970:1970"
    restart: unless-stopped
