services:
  qobuz-dl:
    container_name: angus-music-dl
    image: qobuz-dl
    ports:
     - 3000:3000
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "./navidrome:/data"
      - "/mnt/hdd2/Music:/music:ro"
