- name: Services
  columns:
    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Home Assistant
              url: http://192.168.0.2:8123
              icon: di:home-assistant
            - title: AdGuard Home
              url: http://192.168.0.3:8085
              icon: di:adguard-home
            - title: Immich
              url: http://192.168.0.3:8082
              icon: di:immich
            - title: Nextcloud
              url: https://nextcloud.paillaugue.fr
              icon: di:nextcloud
            - title: Jellyfin
              url: http://192.168.0.3:8080
              icon: di:jellyfin
            - title: Vaultwarden
              url: http://192.168.0.3:8081
              icon: di:vaultwarden
            - title: Open WebUI
              url: http://192.168.0.3:8084/
              icon: di:open-webui-light
            - title: 4get
              url: http://192.168.0.3:8089/
              icon: di:google

        - type: docker-containers
          hide-by-default: true

        - type: monitor
          cache: 1m
          title: TV
          sites:
            - title: Transmission
              url: http://192.168.0.3:8083
              icon: di:transmission
            - title: Jellyfin
              url: http://192.168.0.3:8080
              icon: di:jellyfin
            - title: Sonarr
              url: http://192.168.0.3:8090
              icon: di:sonarr
            - title: Radarr
              url: http://192.168.0.3:8091
              icon: di:radarr
            - title: Bazarr
              url: http://192.168.0.3:8092
              icon: di:bazarr
            - title: Jackett
              url: http://192.168.0.3:8093/UI/Dashboard
              icon: di:jackett
            - title: Jellyseerr
              url: http://192.168.0.3:8094
              icon: di:jellyseerr
