services:
  open-webui:
    container_name: open-webui
   # deploy:
   #   resources:
   #     reservations:
   #       devices:
   #         - driver: nvidia
   #           count: all
   #           capabilities: [gpu]
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "8084:8080"
    volumes:
      - ./open-webui/open-webui:/app/backend/data
    labels:
      glance.name: Open WebUI
      glance.icon: si:openai
      glance.url: http://192.168.0.3:8084
      glance.description: ChatGPT like interface for LLMs
      glance.id: open-webui
      glance.hide: false

  ollama:
    image: ollama/ollama
    container_name: open-webui-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./open-webui/ollama:/root/.ollama
    restart: unless-stopped
    labels:
      glance.parent: open-webui
      glance.name: Ollama
      glance.hide: false

  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./glance/config:/app/config
      - ./glance/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd:/mnt/hdd:ro
      - /mnt/hdd2:/mnt/hdd2:ro
    ports:
      - 8088:8080
    env_file: ./glance/.env
    labels:
      glance.name: Glance
      glance.icon: di:glance-light
      glance.url: http://192.168.0.3:8088
      glance.description: New tab page for your browser
      glance.hide: false

  fourget:
    image: luuul/4get:latest
    container_name: fourget
    restart: unless-stopped
    environment:
      - FOURGET_PROTO=http
      - FOURGET_SERVER_NAME=Angus's server
    ports:
      - "8089:80"
    labels:
      glance.name: 4get
      glance.hide: false
      glance.icon: si:google
      glance.url: http://192.168.0.3:8089
      glance.description: Search engine
